version: "3"
services:
  fider:
    image: fider:latest
    pull_policy: never
    ports:
      - "80:3000"
    environment:
      BASE_URL: "http://localhost:80"
      GO_ENV: "development"
      DATABASE_URL: "postgres://fider:fider_pw@postgres:5432/fider?sslmode=disable"
      JWT_SECRET: "hsjl]W;&ZcHxT&FK;s%bgIQF:#ch=~#Al4:5]N;7V<qPZ3e9lT4'%;go;LIkc%k"
      LOG_LEVEL: "DEBUG"
      LOG_CONSOLE: "true"
      LOG_SQL: "true"
      EMAIL_NOREPLY: "noreply@yourdomain.com"
      EMAIL_SMTP_HOST: "smtp"
      EMAIL_SMTP_PORT: "1025"
    depends_on:
      postgres:
          condition: service_healthy
      smtp:
          condition: service_started
    restart: on-failure
      
  postgres:
    image: postgres:17
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: fider
      POSTGRES_PASSWORD: fider_pw
      POSTGRES_DB: fider
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fider"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  smtp:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres-data: